import datetime
from typing import Optional, List
from sqlmodel import SQLModel

# Base schema with common fields shared across other schemas
class ProjectBase(SQLModel):
    title: str
    description: str
    detailed_content: str
    github_link: Optional[str] = None
    project_link: Optional[str] = None
    technologies: List[str] = []
    is_featured: bool = False

# Schema for creating a new project (data in POST request)
class ProjectCreate(ProjectBase):
    pass

# Schema for updating an existing project (data in PUT/PATCH request)
# All fields are optional to allow for partial updates.
class ProjectUpdate(SQLModel):
    title: Optional[str] = None
    description: Optional[str] = None
    detailed_content: Optional[str] = None
    github_link: Optional[str] = None
    project_link: Optional[str] = None
    technologies: Optional[List[str]] = None
    is_featured: Optional[bool] = None

# Schema for reading a project from the API (data in GET response)
# Includes fields that are generated by the database.
class ProjectRead(ProjectBase):
    id: int
    created_at: datetime.datetime
    updated_at: datetime.datetime
